version: "3.5"

services:
  api01: &api
    build:
      context: ./
      dockerfile: Dockerfile
    hostname: api01
    volumes:
      - ./:/app
    depends_on:
      - db
    network_mode: host
    environment:
      - DB_HOST=0.0.0.0
      - DB_USER=admin
      - DB_PASSWORD=123
      - DB_NAME=rinha_backend
      - DB_PORT=5432
      - SERVER_PORT=9001
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "20MB"

  api02:
    <<: *api
    hostname: api02
    environment:
      - DB_HOST=0.0.0.0
      - DB_USER=admin
      - DB_PASSWORD=123
      - DB_NAME=rinha_backend
      - DB_PORT=5432
      - SERVER_PORT=9002

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx-test.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "10MB"

  db:
    image: postgres:latest
    hostname: db
    command: postgres
    environment:
      - POSTGRES_DB=rinha_backend
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: "500MB"
